services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    environment:
      - WATCHPACK_POLLING=true
    tty: true
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    tty: true

volumes:
  node_modules: