services:
  web:
    build:
      context: ./web/
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app/web/
      - node_modules:/app/web/node_modules
    environment:
      - WATCHPACK_POLLING=true
    tty: true

volumes:
  node_modules: