services:
  app:
    build:
      context: ./app/
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app/
      - node_modules:/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    tty: true

volumes:
  node_modules: