"""update table

Revision ID: 398eddc1875e
Revises: f96e20c0af0b
Create Date: 2025-08-15 05:41:31.673415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # 追加
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '398eddc1875e'
down_revision: Union[str, Sequence[str], None] = 'f96e20c0af0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('about', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('about', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('about', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('about', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
