"""init

Revision ID: 8613e2764ed3
Revises: 
Create Date: 2025-08-14 03:56:18.232932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # 追加


# revision identifiers, used by Alembic.
revision: str = '8613e2764ed3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tech',
    sa.Column('tech', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tech_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tech_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tech')
    # ### end Alembic commands ###
