"""update table

Revision ID: 8ad5d619768d
Revises: 398eddc1875e
Create Date: 2025-08-15 05:56:22.907169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # 追加


# revision identifiers, used by Alembic.
revision: str = '8ad5d619768d'
down_revision: Union[str, Sequence[str], None] = '398eddc1875e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('project', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('skill', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('skill', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill', 'updated_at')
    op.drop_column('skill', 'created_at')
    op.drop_column('project', 'updated_at')
    op.drop_column('project', 'created_at')
    # ### end Alembic commands ###
