"""init

Revision ID: f96e20c0af0b
Revises: 
Create Date: 2025-08-15 05:03:09.446272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # 追加


# revision identifiers, used by Alembic.
revision: str = 'f96e20c0af0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('about', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('about', 'updated_at')
    op.drop_column('about', 'created_at')
    # ### end Alembic commands ###
