"""Create initial tables

Revision ID: e3b22e3915ef
Revises: 
Create Date: 2025-08-12 20:07:21.626860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# 追記
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e3b22e3915ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
